include:
  - board: nice_nano_v2
    shield: totem_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    snippet: studio-rpc-usb-uart
    artifact-name: totme_dongle_oled

  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: totme_left

  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: totme_right

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset_nice_nano_v2 

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_seeeduino_xiao_ble
# there is no settingsreset (needed) for the XIAO
