include:
  - board: xiao_ble
    shield: totem_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: totem_right rgbled_adapter
  - board: xiao_ble
    shield: settings_reset 
  - board: nice_nano
    shield: totem_central dongle_display
    snippet: studio-rpc-usb-uart
    artifact-name: totem_central
  - board: nice_nano
    shield: settings_reset 
# there is no settingsreset (needed) for the XIAO